name = "emoji2svg"
main = "build/dev/javascript/emoji2svg/index.js"
compatibility_date = "2023-09-22"

[observability]
enabled = true

[cache]
enabled = true

[build]
command = "gleam build --target javascript"

[assets]
directory = "./public"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
