name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: false
          gleam-version: "latest"
      - run: gleam deps download
      - uses: oven-sh/setup-bun@v2
      - run: gleam test
      - run: gleam format --check src test
      - run: bun install --frozen-lockfile
      - run: bun run test:workers
